### ISSUE TITLE
 Wildlife Rescue Environment Not Present

### ISSUE THREAD

**Issue by jamesarambam** [yeshenpy/PMIC#2]
Dear Authors,

The environment code for the motivating domain “WildlifeRescue" is not provided in the repository. Could you please share it?

Thanks

**Comment by yeshenpy** [comment]
I apologize for the delay in responding to your message. The Wildlife Rescue task can be found in this repository [https://github.com/tjuHaoXiaotian/GASIL](https://github.com/tjuHaoXiaotian/GASIL). I hope it can help address your concerns.
